version: '3'
services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: "django00"
    volumes:
    # "RUTA/DEL/SERVIDOR:RUTA/DENTRO/DEL/CONTENEDOR"
      - "/home/hazel_mtz/django/library:/usr/src/django/library"
    ports:
    # "PuertoDelServidor:PuertoDelContenedor"
      - "9000:8000"
    network_mode: bridge
